export interface SettingsBusinessRow {
  id: string;
  businessName: string;
  location: string;
  status: "Active" | "Needs setup" | "Inactive" | "Demo";
  type: "Physical location" | "Virtual location";
  createdOn: string;
  createdBy: string;
  timezone: string;
  owner: string;
}

export const SETTINGS_BUSINESS_ROWS: SettingsBusinessRow[] = [
  {
    id: "biz-001",
    businessName: "Rust",
    location: "San Francisco, CA",
    status: "Active",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Akshat Jain",
    timezone: "America/Los_Angeles",
    owner: "Akshat Jain",
  },
  {
    id: "biz-002",
    businessName: "Jacksonville FL",
    location: "Jacksonville, FL",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-003",
    businessName: "New York, NY",
    location: "New York, NY",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Akshat Jain",
    timezone: "America/New_York",
    owner: "Akshat Jain",
  },
  {
    id: "biz-004",
    businessName: "East Elmhurst, NY",
    location: "Queens, NY",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-005",
    businessName: "Penn Station",
    location: "New York, NY",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-006",
    businessName: "Newark, NJ",
    location: "Newark, NJ",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-007",
    businessName: "Houston, TX",
    location: "Houston, TX",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/Chicago",
    owner: "Garima Sharma",
  },
  {
    id: "biz-008",
    businessName: "Atlanta, GA",
    location: "Atlanta, GA",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-009",
    businessName: "Fenway Park",
    location: "Boston, MA",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-010",
    businessName: "Landover, MD",
    location: "Landover, MD",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-011",
    businessName: "Boston, MA",
    location: "Boston, MA",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/New_York",
    owner: "Garima Sharma",
  },
  {
    id: "biz-012",
    businessName: "DFW Airport, TX",
    location: "Dallas, TX",
    status: "Demo",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Garima Sharma",
    timezone: "America/Chicago",
    owner: "Garima Sharma",
  },
  {
    id: "biz-013",
    businessName: "New Zealand Convention Centre",
    location: "Auckland, NZ",
    status: "Inactive",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Jordan Lee",
    timezone: "Pacific/Auckland",
    owner: "Jordan Lee",
  },
  {
    id: "biz-014",
    businessName: "Miami Beach",
    location: "Miami, FL",
    status: "Active",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Taylor Kim",
    timezone: "America/New_York",
    owner: "Taylor Kim",
  },
  {
    id: "biz-015",
    businessName: "Seattle Pier",
    location: "Seattle, WA",
    status: "Active",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Alex Smith",
    timezone: "America/Los_Angeles",
    owner: "Alex Smith",
  },
  {
    id: "biz-016",
    businessName: "Denver Central",
    location: "Denver, CO",
    status: "Needs setup",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Jordan Lee",
    timezone: "America/Denver",
    owner: "Jordan Lee",
  },
  {
    id: "biz-017",
    businessName: "Phoenix North",
    location: "Phoenix, AZ",
    status: "Inactive",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Taylor Kim",
    timezone: "America/Phoenix",
    owner: "Taylor Kim",
  },
  {
    id: "biz-018",
    businessName: "Chicago Loop",
    location: "Chicago, IL",
    status: "Active",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Alex Smith",
    timezone: "America/Chicago",
    owner: "Alex Smith",
  },
  {
    id: "biz-019",
    businessName: "Portland West",
    location: "Portland, OR",
    status: "Needs setup",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Jordan Lee",
    timezone: "America/Los_Angeles",
    owner: "Jordan Lee",
  },
  {
    id: "biz-020",
    businessName: "Nashville Music Row",
    location: "Nashville, TN",
    status: "Inactive",
    type: "Physical location",
    createdOn: "May 06, 2026",
    createdBy: "Taylor Kim",
    timezone: "America/Chicago",
    owner: "Taylor Kim",
  },
];

