let apiResponse = [
    {
        chartCommonConfig: {
            graphId: "chart_message_session_f55e0e1f_2ac7e422_8dd09b78",
            doubleYaxis: true,
            primaryChartStyle: "HORIZONTAL_BAR_CHART",
            reportOverTime: true,
            parserConfig: {
                yAxisOptions: {
                    enableDoubleYAxis: true,
                    leftYAxisOptions: {
                        label: "average rating",
                        min: 0,
                        max: 0,
                    },
                    rightYAxisOptions: {
                        label: "Rating",
                        min: 0,
                        max: 2,
                    },
                },
                graphTitle: "Monthly Review Summary",
                isGroupedArrayWithoutCategoryKey: true,
                seriesDetails: [
                    {
                        name: "total reviews",
                        dataKey: "total_reviews",
                        type: "HORIZONTAL_BAR_CHART",
                        showInLegend: true,
                        yAxis: 0,
                        color: "#7cb5ec",
                        axisLevel: 0,
                    },
                    {
                        name: "responded reviews",
                        dataKey: "responded_reviews",
                        type: "HORIZONTAL_BAR_CHART",
                        showInLegend: true,
                        yAxis: 0,
                        color: "#434348",
                        axisLevel: 0,
                    },
                    {
                        name: "average rating",
                        dataKey: "average_rating",
                        type: "LINE_CHART",
                        showInLegend: true,
                        yAxis: 1,
                        color: "#90ed7d",
                        axisLevel: 1,
                    },
                    {
                        name: "response rate %",
                        dataKey: "response_rate_percent",
                        type: "LINE_CHART",
                        showInLegend: true,
                        yAxis: 1,
                        color: "#f7a35c",
                        axisLevel: 1,
                    },
                ],
                xAxisTitle: "Month",
                yAxisTitles: ["Primary Metrics (e.g., Review Count)", "Secondary Metrics (e.g., Percentages, Ratings)"],
                legendEnabled: true,
                tooltipEnabled: true,
                tooltip: {
                    enabled: true,
                    shared: true,
                    useHTML: true,
                    backgroundColor: "rgba(255, 255, 255, 0.95)",
                    borderColor: "#cccccc",
                    borderRadius: 8,
                    shadow: true,
                    followPointer: true,
                    hideDelay: 200,
                },
            },
            colors: ["#7cb5ec", "#434348", "#90ed7d", "#f7a35c"],
            primaryColor: "#7cb5ec",
        },
        apiData: {
            dataPoints: [
                {
                    actual: {
                        label: "Nov 2024",
                        shortLabel: "Nov 2024",
                        total_reviews: 26,
                        responded_reviews: 14,
                        average_rating: 3.19,
                        response_rate_percent: 53.85,
                    },
                },
                {
                    actual: {
                        label: "Dec 2024",
                        shortLabel: "Dec 2024",
                        total_reviews: 12,
                        responded_reviews: 7,
                        average_rating: 3.5,
                        response_rate_percent: 58.33,
                    },
                },
                {
                    actual: {
                        label: "Jan 2025",
                        shortLabel: "Jan 2025",
                        total_reviews: 42,
                        responded_reviews: 31,
                        average_rating: 3.62,
                        response_rate_percent: 73.81,
                    },
                },
                {
                    actual: {
                        label: "Feb 2025",
                        shortLabel: "Feb 2025",
                        total_reviews: 22,
                        responded_reviews: 11,
                        average_rating: 3.27,
                        response_rate_percent: 50.0,
                    },
                },
                {
                    actual: {
                        label: "Mar 2025",
                        shortLabel: "Mar 2025",
                        total_reviews: 20,
                        responded_reviews: 10,
                        average_rating: 3.65,
                        response_rate_percent: 50.0,
                    },
                },
                {
                    actual: {
                        label: "Apr 2025",
                        shortLabel: "Apr 2025",
                        total_reviews: 40,
                        responded_reviews: 27,
                        average_rating: 3.55,
                        response_rate_percent: 67.5,
                    },
                },
                {
                    actual: {
                        label: "May 2025",
                        shortLabel: "May 2025",
                        total_reviews: 36,
                        responded_reviews: 23,
                        average_rating: 3.92,
                        response_rate_percent: 63.89,
                    },
                },
                {
                    actual: {
                        label: "Jun 2025",
                        shortLabel: "Jun 2025",
                        total_reviews: 14,
                        responded_reviews: 8,
                        average_rating: 3.93,
                        response_rate_percent: 57.14,
                    },
                },
                {
                    actual: {
                        label: "Jul 2025",
                        shortLabel: "Jul 2025",
                        total_reviews: 36,
                        responded_reviews: 24,
                        average_rating: 3.89,
                        response_rate_percent: 66.67,
                    },
                },
                {
                    actual: {
                        label: "Aug 2025",
                        shortLabel: "Aug 2025",
                        total_reviews: 22,
                        responded_reviews: 10,
                        average_rating: 3.86,
                        response_rate_percent: 45.45,
                    },
                },
                {
                    actual: {
                        label: "Sep 2025",
                        shortLabel: "Sep 2025",
                        total_reviews: 17,
                        responded_reviews: 14,
                        average_rating: 3.65,
                        response_rate_percent: 82.35,
                    },
                },
                {
                    actual: {
                        label: "Oct 2025",
                        shortLabel: "Oct 2025",
                        total_reviews: 19,
                        responded_reviews: 16,
                        average_rating: 4.37,
                        response_rate_percent: 84.21,
                    },
                },
            ],
            dateDiff: 11,
            groupByType: "category",
            dataPresent: true,
            totalRecords: 12,
            chartType: "bar",
            categories: ["Nov 2024", "Dec 2024", "Jan 2025", "Feb 2025", "Mar 2025", "Apr 2025", "May 2025", "Jun 2025", "Jul 2025", "Aug 2025", "Sep 2025", "Oct 2025"],
            seriesCount: 4,
        },
    },
];