  let apiResponse = [
      {
          chartCommonConfig: {
              graphId: "chart_message_session_f55e0e1f_252f2cee_079ed205",
              doubleYaxis: true,
              primaryChartStyle: "VERTICAL_BAR_CHART",
              parserConfig: {
                  reportOverTime: true,
                  yAxisOptions: {
                      enableDoubleYAxis: true,
                      leftYAxisOptions: {
                          label: "average rating",
                          min: 0,
                          max: 0,
                      },
                      rightYAxisOptions: {
                          label: "Rating",
                          min: 0,
                          max: 2,
                      },
                  },
                  isGroupedArrayWithoutCategoryKey: true,
                  graphTitle: "Monthly Review Summary",
                  seriesDetails: [
                      {
                          name: "Reviews",
                          type: "column",
                          primary: true,
                          id: "reviews",
                          dataKey: "totalCount",
                          color: "#0099FF",
                          maxPointWidth: 20,
                          axisLevel: 0,
                          stack: "stack1",
                          showInLegend: true,
                          fillColor: {
                              linearGradient: { x1: 0, x2: 1, y1: 0, y2: 1 },
                              stops: [
                                  [0, "rgba(0,153,255,0.1)"],
                                  [1, "rgba(0,153,255,0)"],
                              ],
                          },
                      },
                      {
                          name: "Rating",
                          type: "spline",
                          id: "rating",
                          dataKey: "avgRatingDecimaled",
                          color: "#2C3E91",
                          maxPointWidth: 20,
                          axisLevel: 1,
                          showInLegend: true,
                          fillColor: {
                              linearGradient: { x1: 0, x2: 1, y1: 0, y2: 1 },
                              stops: [
                                  [0, "rgba(44,62,145,0.1)"],
                                  [1, "rgba(44,62,145,0)"],
                              ],
                          },
                      },
                  ],
                  xAxisTitle: "Month",
                  yAxisTitles: ["Primary Metrics (e.g., Review Count)", "Secondary Metrics (e.g., Percentages, Ratings)"],
                  legendEnabled: true,
                  tooltipEnabled: true,
                  tooltip: {
                      enabled: true,
                      shared: true,
                      useHTML: true,
                      backgroundColor: "rgba(255, 255, 255, 0.95)",
                      borderColor: "#cccccc",
                      borderRadius: 8,
                      shadow: true,
                      followPointer: true,
                      hideDelay: 200,
                  },
              },
              colors: ["#7cb5ec", "#434348", "#90ed7d", "#f7a35c"],
              primaryColor: "#7cb5ec",
          },
          apiData: {
              dataPoints: [
                  {
                      actual: {
                          label: "Aug 2024",
                          shortLabel: "Aug '24",
                          totalCount: 9064,
                          avgRating: 4.5,
                          avgRatingDecimaled: 4.48,
                          startDate: "08/21/2024",
                          endDate: "08/31/2024",
                      },
                      projected: 0,
                  },
                  { actual: { label: "Sep 2024", shortLabel: "Sep '24", totalCount: 22552, avgRating: 4.5, avgRatingDecimaled: 4.49, startDate: "09/01/2024", endDate: "09/30/2024" }, projected: 0 },
                  { actual: { label: "Oct 2024", shortLabel: "Oct '24", totalCount: 21417, avgRating: 4.5, avgRatingDecimaled: 4.48, startDate: "10/01/2024", endDate: "10/31/2024" }, projected: 0 },
                  { actual: { label: "Nov 2024", shortLabel: "Nov '24", totalCount: 19256, avgRating: 4.5, avgRatingDecimaled: 4.5, startDate: "11/01/2024", endDate: "11/30/2024" }, projected: 0 },
                  { actual: { label: "Dec 2024", shortLabel: "Dec '24", totalCount: 21593, avgRating: 4.5, avgRatingDecimaled: 4.45, startDate: "12/01/2024", endDate: "12/31/2024" }, projected: 0 },
                  { actual: { label: "Jan 2025", shortLabel: "Jan '25", totalCount: 21650, avgRating: 4.4, avgRatingDecimaled: 4.44, startDate: "01/01/2025", endDate: "01/31/2025" }, projected: 0 },
                  { actual: { label: "Feb 2025", shortLabel: "Feb '25", totalCount: 18972, avgRating: 4.5, avgRatingDecimaled: 4.46, startDate: "02/01/2025", endDate: "02/28/2025" }, projected: 0 },
                  { actual: { label: "Mar 2025", shortLabel: "Mar '25", totalCount: 21420, avgRating: 4.5, avgRatingDecimaled: 4.49, startDate: "03/01/2025", endDate: "03/31/2025" }, projected: 0 },
                  { actual: { label: "Apr 2025", shortLabel: "Apr '25", totalCount: 11725, avgRating: 4.5, avgRatingDecimaled: 4.47, startDate: "04/01/2025", endDate: "04/30/2025" }, projected: 0 },
                  { actual: { label: "May 2025", shortLabel: "May '25", totalCount: 8382, avgRating: 4.3, avgRatingDecimaled: 4.34, startDate: "05/01/2025", endDate: "05/31/2025" }, projected: 0 },
                  { actual: { label: "Jun 2025", shortLabel: "Jun '25", totalCount: 2489, avgRating: 4.7, avgRatingDecimaled: 4.67, startDate: "06/01/2025", endDate: "06/30/2025" }, projected: 0 },
                  { actual: { label: "Jul 2025", shortLabel: "Jul '25", totalCount: 2064, avgRating: 4.8, avgRatingDecimaled: 4.77, startDate: "07/01/2025", endDate: "07/31/2025" }, projected: 0 },
                  { actual: { label: "Aug 2025", shortLabel: "Aug '25", totalCount: 374, avgRating: 4.7, avgRatingDecimaled: 4.7, startDate: "08/01/2025", endDate: "08/21/2025" }, projected: 553 },
              ],
              dateDiff: 365,
              groupByType: "month",
              dataPresent: true,
              totalRecords: 12,
              chartType: "column",
              categories: ["Nov 2024", "Dec 2024", "Jan 2025", "Feb 2025", "Mar 2025", "Apr 2025", "May 2025", "Jun 2025", "Jul 2025", "Aug 2025", "Sep 2025", "Oct 2025"],
              seriesCount: 4,
          },
      },
  ];