    let apiResponse = [
        {
            chartCommonConfig: {
                graphId: "chart_message_session_571ddb1f_deebd044_c545620d",
                doubleYaxis: true,
                primaryChartStyle: "LINE_CHART",
                reportOverTime: true,
                parserConfig: {
                    graphTitle: "Monthly Review Summary",
                    seriesDetails: [
                        {
                            name: "total reviews",
                            dataKey: "total_reviews",
                            type: "LINE_CHART",
                            showInLegend: true,
                            yAxis: 0,
                            axisLevel: 1,
                            color: "#1f77b4",
                        },
                        {
                            name: "responded reviews",
                            dataKey: "responded_reviews",
                            type: "LINE_CHART",
                            showInLegend: true,
                            yAxis: 0,
                            axisLevel: 1,
                            color: "#2ca02c",
                        },
                        {
                            name: "average rating",
                            dataKey: "average_rating",
                            type: "LINE_CHART",
                            showInLegend: true,
                            yAxis: 1,
                            axisLevel: 1,
                            color: "#ff7f0e",
                        },
                        // {
                        //     name: "response rate %",
                        //     dataKey: "response_rate_percent",
                        //     type: "LINE_CHART",
                        //     showInLegend: true,
                        //     yAxis: 1,
                        //     axisLevel: 2,
                        //     color: "#d62728",
                        // },
                    ],
                    xAxisTitle: "Month",
                    yAxisTitles: ["Primary Metrics (e.g., Review Count)", "Secondary Metrics (e.g., Percentages, Ratings)"],
                    legendEnabled: true,
                    tooltipEnabled: true,
                    isGroupedArrayWithoutCategoryKey: true,
                    dataFormat: "arrayWithKeyValue",
                    tooltip: {
                        enabled: true,
                        shared: true,
                        useHTML: true,
                        backgroundColor: "rgba(255, 255, 255, 0.95)",
                        borderColor: "#cccccc",
                        borderRadius: 8,
                        shadow: true,
                        followPointer: true,
                        hideDelay: 200,
                    },
                    yAxisOptions: {
                        enableDoubleYAxis: true,
                        leftYAxisOptions: {
                            label: ["Total Reviews", "Responded Reviews"],
                            min: 0,
                            max: 0,
                        },
                        rightYAxisOptions: {
                            label: ["Average Rating", "Response Rate %"],
                            min: 0,
                            max: 0,
                        },
                    },
                },
                colors: ["#1f77b4", "#2ca02c", "#ff7f0e", "#d62728"],
                primaryColor: "#1f77b4",
            },
            apiData: {
                dataPoints: [
                    {
                        actual: {
                            label: "Nov 2024",
                            shortLabel: "Nov 2024",
                            total_reviews: 24,
                            responded_reviews: 12,
                            average_rating: 3.21,
                            response_rate_percent: 50,
                        },
                    },
                    {
                        actual: {
                            label: "Dec 2024",
                            shortLabel: "Dec 2024",
                            total_reviews: 12,
                            responded_reviews: 7,
                            average_rating: 3.5,
                            response_rate_percent: 58.33,
                        },
                    },
                    {
                        actual: {
                            label: "Jan 2025",
                            shortLabel: "Jan 2025",
                            total_reviews: 42,
                            responded_reviews: 31,
                            average_rating: 3.62,
                            response_rate_percent: 73.81,
                        },
                    },
                    {
                        actual: {
                            label: "Feb 2025",
                            shortLabel: "Feb 2025",
                            total_reviews: 22,
                            responded_reviews: 11,
                            average_rating: 3.27,
                            response_rate_percent: 50,
                        },
                    },
                    {
                        actual: {
                            label: "Mar 2025",
                            shortLabel: "Mar 2025",
                            total_reviews: 19,
                            responded_reviews: 9,
                            average_rating: 3.79,
                            response_rate_percent: 47.37,
                        },
                    },
                    {
                        actual: {
                            label: "Apr 2025",
                            shortLabel: "Apr 2025",
                            total_reviews: 40,
                            responded_reviews: 27,
                            average_rating: 3.55,
                            response_rate_percent: 67.5,
                        },
                    },
                    {
                        actual: {
                            label: "May 2025",
                            shortLabel: "May 2025",
                            total_reviews: 36,
                            responded_reviews: 23,
                            average_rating: 3.92,
                            response_rate_percent: 63.89,
                        },
                    },
                    {
                        actual: {
                            label: "Jun 2025",
                            shortLabel: "Jun 2025",
                            total_reviews: 14,
                            responded_reviews: 8,
                            average_rating: 3.93,
                            response_rate_percent: 57.14,
                        },
                    },
                    {
                        actual: {
                            label: "Jul 2025",
                            shortLabel: "Jul 2025",
                            total_reviews: 36,
                            responded_reviews: 24,
                            average_rating: 3.89,
                            response_rate_percent: 66.67,
                        },
                    },
                    {
                        actual: {
                            label: "Aug 2025",
                            shortLabel: "Aug 2025",
                            total_reviews: 22,
                            responded_reviews: 10,
                            average_rating: 3.86,
                            response_rate_percent: 45.45,
                        },
                    },
                    {
                        actual: {
                            label: "Sep 2025",
                            shortLabel: "Sep 2025",
                            total_reviews: 20,
                            responded_reviews: 14,
                            average_rating: 3.5,
                            response_rate_percent: 70,
                        },
                    },
                    {
                        actual: {
                            label: "Oct 2025",
                            shortLabel: "Oct 2025",
                            total_reviews: 27,
                            responded_reviews: 18,
                            average_rating: 3.96,
                            response_rate_percent: 66.67,
                        },
                    },
                ],
                dateDiff: 11,
                groupByType: "category",
                dataPresent: true,
                totalRecords: 12,
                chartType: "line",
                categories: ["Nov 2024", "Dec 2024", "Jan 2025", "Feb 2025", "Mar 2025", "Apr 2025", "May 2025", "Jun 2025", "Jul 2025", "Aug 2025", "Sep 2025", "Oct 2025"],
                seriesCount: 4,
            },
        },
    ];