import React, { useState } from 'react';
import AiContentDrawer from './index';

export default {
  title: 'Component/AiContentDrawer',
  component: AiContentDrawer,
  parameters: {
    layout: 'fullscreen',
  },
  argTypes: {
    onClose: { action: 'closed' },
    onRegenerate: { action: 'regenerated' },
    onInsert: { action: 'inserted' },
    onSelectItem: { action: 'item selected' },
  },
};

// Mock Data
const mockItems = [
  {
    id: 1,
    description: '<p><strong>Option 1:</strong> This is a professional response generated by AI. It highlights the key benefits of the product while maintaining a formal tone.</p>',
  },
  {
    id: 2,
    description: '<p><strong>Option 2:</strong> Hey there! This version is much more casual and friendly, perfect for social media engagement or direct messaging.</p>',
  },
  {
    id: 3,
    description: '<p><strong>Option 3:</strong> A concise, bulleted version:</p><ul><li>Fast delivery</li><li>High quality</li><li>Eco-friendly materials</li></ul>',
  }
];

// Template for interactive state management
const Template = (args) => {
  const [isOpen, setIsOpen] = useState(true);
  const [selectedIndex, setSelectedIndex] = useState(args.selectedIndex || 1);

  const handleSelect = (id) => {
    setSelectedIndex(id);
    args.onSelectItem(id);
  };

  return (
    <div style={{ height: '100vh', background: '#f0f2f5', padding: '20px' }}>
      <button onClick={() => setIsOpen(true)}>Open AI Drawer</button>
      <AiContentDrawer
        {...args}
        isOpen={isOpen}
        onClose={() => setIsOpen(false)}
        selectedIndex={selectedIndex}
        onSelectItem={handleSelect}
      />
    </div>
  );
};

export const Default = Template.bind({});
Default.args = {
  title: 'AI Content Assistant',
  items: mockItems,
  maxRegenerateCount: 5,
  regenerateCount: 2,
};

export const LoadingState = Template.bind({});
LoadingState.args = {
  title: 'Generating Content...',
  items: [mockItems[0]],
  isLoading: true,
  loadingText: 'Our AI is thinking of more options...',
};

export const WithCustomInput = Template.bind({});
WithCustomInput.args = {
  title: 'Rephrase with Context',
  items: mockItems,
  customInputRender: () => (
    <div style={{ padding: '12px', background: '#f9f9f9', borderRadius: '8px', border: '1px dashed #ccc' }}>
      <label style={{ fontSize: '12px', fontWeight: '500', display: 'block', marginBottom: '4px' }}>
        Tone Adjustment
      </label>
      <select style={{ width: '100%', padding: '8px', borderRadius: '4px' }}>
        <option>Professional</option>
        <option>Witty</option>
        <option>Urgent</option>
      </select>
    </div>
  ),
};

export const LimitReached = Template.bind({});
LimitReached.args = {
  title: 'Daily Limit Reached',
  items: mockItems,
  maxRegenerateCount: 5,
  regenerateCount: 5, // This will disable the regenerate button
};

export const EmptyState = Template.bind({});
EmptyState.args = {
  title: 'No Content Yet',
  items: [],
  children: (
    <div style={{ textAlign: 'center', marginTop: '40px', color: '#999' }}>
      <i className="icon_phoenix-info" style={{ fontSize: '48px' }} />
      <p>Click regenerate to start creating content.</p>
    </div>
  ),
};