export const wordCloudReportConfig = {
    tempUniqueId: "sentiment_score_top_themes-175333710077097",
    parserConfig: {
        chart: {
            scrollablePlotArea: {
                minWidth: 1200,
                opacity: 1,
            },
        },
        chartVisualisationConfig: {
            defaultType: {
                value: "wordcloud",
            },
        },
        downloadActionsConfig: {
            show: false,
        },
        title: "What are the top themes for",
        primaryChartStyle: "wordcloud",
        disableWordCloudClick: true,
        seriesDetails: [
            {
                name: "WordCloud",
                type: "wordcloud",
                minFontSize: 6,
                maxFontSize: 24,
                rotation: {
                    from: 0,
                    to: 0,
                    orientations: 1,
                },
                spiral: "rectangular",
                placementStrategy: "center",
                dataKey: "mentions",
            },
        ],
        plotDataConfig: {
            wordcloud: {
                animation: false,
            },
        },
    },
    filterData: {
        catIds: [22406],
        timePeriodSelected: "all",
        excludedBizIds: [],
        cityStateData: {},
        businessIds: [],
        reviewSiteIds: [
            "2",
            "1",
            "110",
            "100",
            "342",
            "266",
            "91",
            "273",
            "214",
            "30",
            "211",
            "47",
            "157",
            "3",
            "130",
            "107",
            "295",
            "144",
            "399",
            "15",
            "68",
            "411",
            "279",
            "345",
            "10",
            "407",
            "72",
            "294",
            "208",
            "28",
            "38",
            "111",
            "277",
            "49",
            "403",
            "82",
            "8",
            "114",
            "311",
            "6",
            "57",
            "45",
            "33",
            "418",
            "396",
            "174",
            "118",
            "142",
            "339",
            "58",
            "395",
            "333",
            "139",
            "150",
            "213",
            "412",
            "290",
            "131",
            "406",
            "52",
            "143",
            "202",
            "189",
            "88",
            "261",
            "405",
            "115",
            "16",
            "215",
            "25",
            "349",
            "9",
            "312",
            "207",
            "78",
            "97",
            "325",
            "89",
            "103",
            "21",
            "283",
            "24",
            "4",
            "5",
            "63",
            "32",
            "392",
        ],
        categoryIds: [22406],
        newFilters: true,
        customLevelData: [],
        key: "all_time",
    },
    apiData: {
        totalCount: 20029,
        sentiment: {
            spread: {
                pos: 18879,
                neg: 706,
                neu: 444,
            },
        },
        themes: {
            POSITIVE: [
                {
                    id: "friendly#~staff",
                    name: "friendly staff",
                    mentions: 2542,
                },
                {
                    id: "great#~customer service",
                    name: "great customer service",
                    mentions: 1692,
                },
                {
                    id: "excellent#~customer service",
                    name: "excellent customer service",
                    mentions: 1248,
                },
                {
                    id: "helpful#~staff",
                    name: "helpful staff",
                    mentions: 807,
                },
                {
                    id: "nice#~person",
                    name: "nice person",
                    mentions: 582,
                },
                {
                    id: "great#~staff",
                    name: "great staff",
                    mentions: 499,
                },
                {
                    id: "nice#~staff",
                    name: "nice staff",
                    mentions: 477,
                },
                {
                    id: "great#~person",
                    name: "great person",
                    mentions: 408,
                },
                {
                    id: "good#~customer service",
                    name: "good customer service",
                    mentions: 370,
                },
                {
                    id: "recommend#~company",
                    name: "recommend company",
                    mentions: 348,
                },
                {
                    id: "friendly#~person",
                    name: "friendly person",
                    mentions: 327,
                },
                {
                    id: "professional#~staff",
                    name: "professional staff",
                    mentions: 269,
                },
                {
                    id: "great#~company",
                    name: "great company",
                    mentions: 223,
                },
                {
                    id: "very professional#~staff",
                    name: "very professional staff",
                    mentions: 221,
                },
                {
                    id: "amazing#~staff",
                    name: "amazing staff",
                    mentions: 194,
                },
                {
                    id: "polite#~staff",
                    name: "polite staff",
                    mentions: 185,
                },
                {
                    id: "kind#~staff",
                    name: "kind staff",
                    mentions: 183,
                },
                {
                    id: "great#~team",
                    name: "great team",
                    mentions: 174,
                },
                {
                    id: "awesome#~customer service",
                    name: "awesome customer service",
                    mentions: 173,
                },
                {
                    id: "excellent#~staff",
                    name: "excellent staff",
                    mentions: 157,
                },
                {
                    id: "knowledgeable#~staff",
                    name: "knowledgeable staff",
                    mentions: 151,
                },
                {
                    id: "good#~person",
                    name: "good person",
                    mentions: 150,
                },
                {
                    id: "wonderful#~staff",
                    name: "wonderful staff",
                    mentions: 139,
                },
                {
                    id: "pleasant#~staff",
                    name: "pleasant staff",
                    mentions: 136,
                },
                {
                    id: "good#~staff",
                    name: "good staff",
                    mentions: 135,
                },
                {
                    id: "friendly#~customer service",
                    name: "friendly customer service",
                    mentions: 131,
                },
                {
                    id: "wonderful#~customer service",
                    name: "wonderful customer service",
                    mentions: 127,
                },
                {
                    id: "friendly#~employee",
                    name: "friendly employee",
                    mentions: 117,
                },
                {
                    id: "courteous#~staff",
                    name: "courteous staff",
                    mentions: 115,
                },
                {
                    id: "best#~customer service",
                    name: "best customer service",
                    mentions: 109,
                },
                {
                    id: "awesome#~staff",
                    name: "awesome staff",
                    mentions: 107,
                },
                {
                    id: "attentive#~staff",
                    name: "attentive staff",
                    mentions: 100,
                },
                {
                    id: "amazing#~customer service",
                    name: "amazing customer service",
                    mentions: 100,
                },
                {
                    id: "outstanding#~customer service",
                    name: "outstanding customer service",
                    mentions: 89,
                },
                {
                    id: "helpful#~person",
                    name: "helpful person",
                    mentions: 77,
                },
                {
                    id: "efficient#~staff",
                    name: "efficient staff",
                    mentions: 66,
                },
                {
                    id: "exceptional#~customer service",
                    name: "exceptional customer service",
                    mentions: 65,
                },
                {
                    id: "caring#~staff",
                    name: "caring staff",
                    mentions: 64,
                },
                {
                    id: "friendly#~customer",
                    name: "friendly customer",
                    mentions: 62,
                },
                {
                    id: "recommend#~person",
                    name: "recommend person",
                    mentions: 57,
                },
                {
                    id: "easy#~staff",
                    name: "easy staff",
                    mentions: 57,
                },
                {
                    id: "helpful#~employee",
                    name: "helpful employee",
                    mentions: 55,
                },
                {
                    id: "amazing#~person",
                    name: "amazing person",
                    mentions: 51,
                },
                {
                    id: "more#~business",
                    name: "more business",
                    mentions: 44,
                },
            ],
            NEGATIVE: [
                {
                    id: "more#~staff",
                    name: "more staff",
                    mentions: 33,
                },
            ],
        },
    },
    visualisationType: "chart",
    graphTitleTooltipText: "This word cloud highlights frequently mentioned topics in your customer feedback, color-coded for sentiment.",
    apiDetails: {
        url: "insight/theme/all",
        method: "post",
        params: {
            "page-size": 45,
        },
    },
    pageTitle: "Recommendations",
    graphId: "sentiment_score_top_themes",
    title: "What are the top themes for",
};
