const TOKEN_MENU_TYPE = {
    SMS_BODY: "SMS_BODY",
    CUSTOM_HTML: "CUSTOM_HTML",
    CUSTOM_SMS_TEMPLATE: "CUSTOM_SMS_TEMPLATE",
    CUSTOM_VOICE_MAIL: "CUSTOM_VOICE_MAIL",
    AUTO_REPLY: "AUTO_REPLY",
    FAQ: "FAQ",
    GMB_OPTIONS: "GMB_OPTIONS",
    SOCIAL_POST_OPTIONS: "SOCIAL_POST_OPTIONS",
    SURVEY_QUESTION_TITLE: "SURVEY_QUESTION_TITLE",
    SURVEY_TITLE: "SURVEY_TITLE",
    FORM_URL: "FORM_URL"
};

const MODULE_CONSTANTS = {
    APPOINTMENT_REMINDER_SMS: "appointment_reminder_sms",
    APPOINTMENT_REMINDER_EMAIL: "appointment_reminder",
    REVIEW_REQUEST_SMS: "review_request_sms",
    APPOINTMENT_FORM_SMS: "appointment_form_sms",
    APPOINTMENT_FORM_EMAIL: "appointment_form",
    APPOINTMENT_RECALL_SMS: "appointment_recall_sms",
    APPOINTMENT_RECALL_EMAIL: "appointment_recall",
    REVIEW_REQUEST_EMAIL: "review_request_email",
}

const CUSTOM_VALUES_TYPE = {
    LIST_TEXT: "list_text"
};

export { TOKEN_MENU_TYPE, MODULE_CONSTANTS, CUSTOM_VALUES_TYPE }