import { benevoPink, brightGreen, pastelViolet } from "components/GraphTable/common/colors";
import { gray50 } from "sass/js/colors";

export const groupedColumnReportData = {
    disableEmailBodyEdit: false,
    tempUniqueId: "repuationScoreOverTimeDetails1751000611910116",
    parserConfig: {
        disableCompareChart: true,
        xAxisConfig: {
            enabled: false,
        },
        maxPointWidth: 30,
        legendValue: ["Sentiment Score", "Reputation Score", "Listing Score", /* "Survey Score", "Calls Score", "Social Score",*/ "Industry Average"],
        barGrouping: true,
        dataFormat: "arrayWithKeyValue",
        displaySummary: false,
        crosshairConfig: {
            color: "#e3effc",
        },
        yAxisCustomMax: function (max1, max2) {
            max1 = max1 + Math.ceil((max1 / 100) * 15);
            return {
                max1,
                max2,
            };
        },
        showProjectedData: false,
        enableDataLabelRotation: true,
        yAxisText: "",
        stackedGraph: true,
        addPositionerInTooltip: true,
        doubleYaxis: false,
        graphTitle: "Birdeye Score over time",
        xAxisLabelsAlignment: {
            bar: "right",
            column: "center",
            spline: "right",
            areaspline: "right",
        },
        seriesDetails: [
            {
                name: "Sentiment score",
                primary: true,
                maxPointWidth: 20,
                type: "column",
                showInLegend: true,
                id: "birdeyeScore",
                pointPlacement: 0.2,
                dataKey: "sentimentScore",
                color: pastelViolet,
                zIndex: 1,
                toolTipLabel: "Your score",
            },
            {
                name: "Reputation score",
                primary: true,
                maxPointWidth: 20,
                type: "column",
                yAxisLabel: "",
                yAxis: 0,
                showInLegend: true,
                id: "birdeyeScore",
                pointPlacement: 0.2,
                dataKey: "reputationScore",
                zIndex: 1,
                color: benevoPink,
                toolTipLabel: "Your score",
            },
            {
                name: "Listing score",
                primary: true,
                maxPointWidth: 20,
                type: "column",
                yAxisLabel: "",
                yAxis: 0,
                showInLegend: true,
                id: "birdeyeScore",
                pointPlacement: 0.2,
                dataKey: "listingScore",
                zIndex: 1,
                color: brightGreen,
                toolTipLabel: "Your score",
            },
            // {
            //     name: "Survey score",
            //     primary: true,
            //     maxPointWidth: 20,
            //     type: "column",
            //     yAxisLabel: "",
            //     yAxis: 0,
            //     showInLegend: true,
            //     id: "birdeyeScore",
            //     pointPlacement: 0.2,
            //     dataKey: "surveyScore",
            //     zIndex: 1,
            //     color: sunflower,
            //     toolTipLabel: "Your score",
            // },
            // {
            //     name: "Calls score",
            //     primary: true,
            //     maxPointWidth: 20,
            //     type: "column",
            //     showInLegend: true,
            //     id: "birdeyeScore",
            //     pointPlacement: 0.2,
            //     dataKey: "callsScore",
            //     zIndex: 1,
            //     color: turqouise,
            //     toolTipLabel: "Your score",
            // },
            // {
            //     name: "Social score",
            //     primary: true,
            //     maxPointWidth: 20,
            //     type: "column",
            //     showInLegend: true,
            //     id: "birdeyeScore",
            //     pointPlacement: 0.2,
            //     dataKey: "socialScore",
            //     zIndex: 1,
            //     color: carrot,
            //     toolTipLabel: "Your score",
            // },
            {
                primary: true,
                name: "Industry average",
                maxPointWidth: 40,
                type: "column",
                yAxisLabel: "",
                color: gray50,
                showInLegend: true,
                id: "industryAverage",
                dataKey: "industryAverage",
                pointPlacement: 0.2,
                zIndex: 0,
                toolTipLabel: "Industry average",
            },
        ],
        getSpaceMultiplier: () => {
            return 80;
        },
        getDataMultiplier: (primaryChartStyle) => {
            if (primaryChartStyle == "bar" || primaryChartStyle == "column") {
                return 3;
            } else {
                return 1;
            }
        },
        isCustomSpaceMultiplier: true,
        dataPoints: true,
        reversedStacks: false,
        plotDataConfig: {
            column: {
                dataLabels: {
                    enabled: true,
                    rotation: 0,
                    verticalAlign: "top",
                    y: -30,
                    align: null,
                    color: "#212121",
                    fontSize: "12px",
                    fontWeight: 400,
                    crop: false,
                    overflow: "allow",
                    inside: false,
                },
            },
            bar: {
                dataLabels: {
                    enabled: true,
                    rotation: 0,
                    align: null,
                    color: "#212121",
                    fontSize: "12px",
                    fontWeight: 400,
                    crop: false,
                    overflow: "allow",
                    inside: false,
                },
            },
        },
        spacingBottom: 10,
        marginRight: 0,
        xAxisLabelsWidth: {
            bar: 120,
            column: 90,
        },
        removeZeroValueData: false,
        enableScroll: true,
        lineBubbles: true,
        defaultChartStyle: "column",
        primaryChartStyle: "column",
        marginLeft: 0,
        reportOverTime: false,
        xAxisLabelsRotation: {
            bar: -90,
            column: -90,
            spline: -90,
            areaspline: -90,
            tickInterval: 1,
            defaultRotation: -90,
            align: "center",
        },
        hideDottedLastLine: true,
        spacingRight: 0,
        yAxisTickInterval: 20,
        yAxisConfig: {
            enabled: true,
        },
        enableCrosshair: true,
        reverseLegendOrder: false,
    },
    heading: "Birdeye Score over time",
    apiData: {
        summary: {
            actual: {
                birdeyeScoreBreakdown: {
                    sentimentScore: 100,
                    reputationScore: 90,
                    listingScore: 50,
                    // surveyScore: 80,
                    // callsScore: 70,
                    // socialScore: 300,
                },
            },
            compare: {
                birdeyeScoreBreakdown: {
                    sentimentScore: 90,
                    reputationScore: 85,
                    listingScore: 45,
                    // surveyScore: 75,
                    // callsScore: 65,
                    // socialScore: 280,
                },
            },
        },
        dataPoints: [
            {
                actual: {
                    sentimentScore: 100,
                    industryAverage: 190,
                },
            },
            {
                actual: {
                    reputationScore: 90,
                    industryAverage: 85,
                },
            },
            {
                actual: {
                    listingScore: 50,
                    industryAverage: 85,
                },
            },
        ],
    },
    legendValue: ["Birdeye Score", "Industry average"],
    yAxisOptions: {
        enableDoubleYAxis: false,
        leftYAxisOptions: {
            label: "",
            min: 0,
            max: 110,
        },
        rightYAxisOptions: null,
    },
    isCustomLegend: true,
    apiDetails: {
        url: "api/insight/experience/over-time",
        breakdownUrl: "api/insight/experience/breakdown/over-time",
        industryAvgUrl: "api/insight/experience/industry/over-time",
        method: "post",
    },
    graphId: "insights-experience-score-over-time",
    redirectURL: "",
    extraReqParams: {},
    showDelta: true,
    chartActions: [{}],
    globalFilters: {},
    cardConfig: {
        width: 1127,
        height: 490,
        isDynamicTableHeight: true,
    },
    multiChartId: "reputation-score-over-time",
    hideSummary: false,
    step: null,
    disablePNG: true,
    disablePPT: true,
    isInsightPage: true,
    showActionsDownload: true,
    disableActionForNoData: true,
    filterCount: {},
    isFullWidthEnabled: true,
    router: "/dashboard/insights-analytics/experience",
    createdBy: "",
    disabledSeriesData: [],
};
