export const splineReportdata = {
    reportsGroup: "channels",
    tempUniqueId: "channels-received-messages_175117065959386",
    subReportsGroup: "channels",
    parserConfig: {
        dataFormat: "arrayWithGrouped",
        categoryKey: "subDataPoints",
        displaySummary: true,
        crosshairConfig: {
            color: "#e3effc",
        },
        getSpaceMultiplier: () => {
            return 80;
        },
        getDataMultiplier: (primaryChartStyle) => {
            if (primaryChartStyle == "bar" || primaryChartStyle == "column") {
                return 3;
            } else {
                return 1;
            }
        },
        yAxisCustomMax: function (max1, max2) {
            max1 = max1 + Math.ceil((max1 / 100) * 15);
            return {
                max1,
                max2,
            };
        },
        showProjectedData: false,
        colorAxisConfig: {
            min: 0,
            minColor: "#ffffff",
            maxColor: "#3790e7",
            labels: {
                style: {
                    fontSize: "12px",
                    fontWeight: 400,
                    color: "#555",
                },
            },
        },
        stackedGraph: true,
        addPositionerInTooltip: true,
        categoryValueMap: {
            THU: {
                value: "Thu",
                color: "#ff6a4d",
            },
            WEB_CHAT: {
                value: "Chatbot AI",
                color: "#2C3E91",
            },
            TUE: {
                value: "Tue",
                color: "#ff6a4d",
            },
            FACEBOOK: {
                value: "Facebook",
                color: "#FBC123",
            },
            SAT: {
                value: "Sat",
                color: "#ff6a4d",
            },
            VOICE_CALL: {
                value: "Voice call",
                color: "#70156C",
            },
            SUN: {
                value: "Sun",
                color: "#ff6a4d",
            },
            MON: {
                value: "Mon",
                color: "#ff6a4d",
            },
            INSTAGRAM: {
                value: "Instagram",
                color: "#FF6A4D",
            },
            TWITTER: {
                value: "X (Twitter)",
                color: "#7ED321",
            },
            WED: {
                value: "Wed",
                color: "#ff6a4d",
            },
            SMS: {
                value: "Text",
                color: "#34D1BF",
            },
            GOOGLE: {
                value: "Google",
                color: "#4CAE3D",
            },
            APPLE: {
                value: "Apple messages",
                color: "#1877F2",
            },
            EMAIL: {
                value: "Email",
                color: "#DE0D92",
            },
            FRI: {
                value: "Fri",
                color: "#ff6a4d",
            },
            CONTACT_US: {
                value: "Webforms",
                color: "#6665DD",
            },
            APPOINTMENT: {
                value: "Appointments",
                color: "#0099FF",
            },
        },
        tickWidth: 1,
        graphTitle: "Messages received by channel",
        xAxisLabelsAlignment: {
            bar: "right",
            column: "right",
            line: "right",
        },
        seriesDetails: [
            {
                convertDataToArray: true,
                primary: true,
                color: "#2C3E91",
                name: "Chatbot AI",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "WEB_CHAT",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#FBC123",
                name: "Facebook",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "FACEBOOK",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#70156C",
                name: "Voice call",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "VOICE_CALL",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#FF6A4D",
                name: "Instagram",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "INSTAGRAM",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#7ED321",
                name: "X (Twitter)",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "TWITTER",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#34D1BF",
                name: "Text",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "SMS",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#4CAE3D",
                name: "Google",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "GOOGLE",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#1877F2",
                name: "Apple messages",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "APPLE",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#DE0D92",
                name: "Email",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "EMAIL",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#6665DD",
                name: "Webforms",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "CONTACT_US",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
            {
                convertDataToArray: true,
                primary: true,
                color: "#0099FF",
                name: "Appointments",
                tableViewkey: "countOrderData",
                dataKey: "subDataPoints",
                subDataKey: "APPOINTMENT",
                maxPointWidth: 20,
                type: "spline",
                yAxisLabel: "Reviews",
                id: "barProjected",
                compareColor: "red",
            },
        ],
        dataPoints: true,
        plotDataConfig: {
            spline: {},
        },
        spacingBottom: 0,
        marginRight: 0,
        xAxisLabelsWidth: {
            bar: 120,
            column: 90,
        },
        removeZeroValueData: false,
        summaryData: [
            {
                label: "Messages received",
                dataKey: "totalCount",
                showChange: false,
            },
        ],
        tableConfig: {
            actual: [
                {
                    dataLabel: "Date",
                    dataKey: "label",
                    width: 200,
                    enableSort: true,
                    columnKey: "date",
                },
                {
                    dataLabel: "Total",
                    dataKey: "totalCount",
                    width: 100,
                    enableSort: true,
                    columnKey: "count",
                },
                {
                    dataLabel: "Chatbot AI",
                    dataKey: "subDataPoints",
                    dataIndex: 0,
                    width: 80,
                    enableSort: false,
                    columnKey: "WEB_CHAT",
                },
                {
                    dataLabel: "Facebook",
                    dataKey: "subDataPoints",
                    dataIndex: 1,
                    width: 80,
                    enableSort: false,
                    columnKey: "FACEBOOK",
                },
                {
                    dataLabel: "Voice call",
                    dataKey: "subDataPoints",
                    dataIndex: 2,
                    width: 80,
                    enableSort: false,
                    columnKey: "VOICE_CALL",
                },
                {
                    dataLabel: "Instagram",
                    dataKey: "subDataPoints",
                    dataIndex: 3,
                    width: 80,
                    enableSort: false,
                    columnKey: "INSTAGRAM",
                },
                {
                    dataLabel: "X (Twitter)",
                    dataKey: "subDataPoints",
                    dataIndex: 4,
                    width: 80,
                    enableSort: false,
                    columnKey: "TWITTER",
                },
                {
                    dataLabel: "Text",
                    dataKey: "subDataPoints",
                    dataIndex: 5,
                    width: 80,
                    enableSort: false,
                    columnKey: "SMS",
                },
                {
                    dataLabel: "Google",
                    dataKey: "subDataPoints",
                    dataIndex: 6,
                    width: 80,
                    enableSort: false,
                    columnKey: "GOOGLE",
                },
                {
                    dataLabel: "Apple messages",
                    dataKey: "subDataPoints",
                    dataIndex: 7,
                    width: 120,
                    enableSort: false,
                    columnKey: "APPLE",
                },
                {
                    dataLabel: "Email",
                    dataKey: "subDataPoints",
                    dataIndex: 8,
                    width: 80,
                    enableSort: false,
                    columnKey: "EMAIL",
                },
                {
                    dataLabel: "Webforms",
                    dataKey: "subDataPoints",
                    dataIndex: 9,
                    width: 80,
                    enableSort: false,
                    columnKey: "CONTACT_US",
                },
                {
                    dataLabel: "Appointments",
                    dataKey: "subDataPoints",
                    dataIndex: 10,
                    width: 80,
                    enableSort: false,
                    columnKey: "APPOINTMENT",
                },
            ],
        },
        enableScroll: true,
        defaultChartStyle: "area",
        primaryChartStyle: "spline",
        marginLeft: 0,
        reportOverTime: true,
        xAxisLabelsRotation: {
            bar: -45,
            column: -90,
            line: -90,
            tickInterval: 1,
            defaultRotation: -45,
            align: "right",
        },
        hideDottedLastLine: false,
        customContainerClasses: "show-legend-items",
        customToolTipFormatter: true,
        showTotalForStackOnTooltip: true,
        compareStacking: "normal",
        enableCrosshair: true,
        reverseLegendOrder: false,
    },
    displayValueAs: {
        days: false,
        hours: false,
        minutes: false,
    },
    heading: "Messages received by channel",
    actualAndCompareWith: {},
    globalFilterApplied: true,
    apiData: {
        summary: {
            actual: {
                totalCount: 787,
                thisMonth: 84,
                lastOneYear: 0,
            },
            compare: {},
        },
        dataPoints: [
            {
                actual: {
                    label: "Jun 2024",
                    shortLabel: "Jun '24",
                    totalCount: 12,
                    startDate: "06/28/2024",
                    endDate: "06/30/2024",
                    dynamicLabel: {
                        header: "label",
                        value: "Jun 2024",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 0,
                        FACEBOOK: 0,
                        VOICE_CALL: 3,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 9,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Jul 2024",
                    shortLabel: "Jul '24",
                    totalCount: 128,
                    startDate: "07/01/2024",
                    endDate: "07/31/2024",
                    dynamicLabel: {
                        header: "label",
                        value: "Jul 2024",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 1,
                        FACEBOOK: 10,
                        VOICE_CALL: 17,
                        INSTAGRAM: 11,
                        TWITTER: 0,
                        SMS: 89,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Aug 2024",
                    shortLabel: "Aug '24",
                    totalCount: 41,
                    startDate: "08/01/2024",
                    endDate: "08/31/2024",
                    dynamicLabel: {
                        header: "label",
                        value: "Aug 2024",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 0,
                        FACEBOOK: 0,
                        VOICE_CALL: 18,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 22,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 1,
                    },
                },
            },
            {
                actual: {
                    label: "Sep 2024",
                    shortLabel: "Sep '24",
                    totalCount: 84,
                    startDate: "09/01/2024",
                    endDate: "09/30/2024",
                    dynamicLabel: {
                        header: "label",
                        value: "Sep 2024",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 55,
                        FACEBOOK: 0,
                        VOICE_CALL: 18,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 11,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Oct 2024",
                    shortLabel: "Oct '24",
                    totalCount: 43,
                    startDate: "10/01/2024",
                    endDate: "10/31/2024",
                    dynamicLabel: {
                        header: "label",
                        value: "Oct 2024",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 7,
                        FACEBOOK: 1,
                        VOICE_CALL: 22,
                        INSTAGRAM: 7,
                        TWITTER: 1,
                        SMS: 5,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Nov 2024",
                    shortLabel: "Nov '24",
                    totalCount: 73,
                    startDate: "11/01/2024",
                    endDate: "11/30/2024",
                    dynamicLabel: {
                        header: "label",
                        value: "Nov 2024",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 15,
                        FACEBOOK: 4,
                        VOICE_CALL: 35,
                        INSTAGRAM: 6,
                        TWITTER: 0,
                        SMS: 13,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Dec 2024",
                    shortLabel: "Dec '24",
                    totalCount: 111,
                    startDate: "12/01/2024",
                    endDate: "12/31/2024",
                    dynamicLabel: {
                        header: "label",
                        value: "Dec 2024",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 6,
                        FACEBOOK: 0,
                        VOICE_CALL: 95,
                        INSTAGRAM: 4,
                        TWITTER: 0,
                        SMS: 6,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Jan 2025",
                    shortLabel: "Jan '25",
                    totalCount: 92,
                    startDate: "01/01/2025",
                    endDate: "01/31/2025",
                    dynamicLabel: {
                        header: "label",
                        value: "Jan 2025",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 3,
                        FACEBOOK: 5,
                        VOICE_CALL: 69,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 15,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Feb 2025",
                    shortLabel: "Feb '25",
                    totalCount: 42,
                    startDate: "02/01/2025",
                    endDate: "02/28/2025",
                    dynamicLabel: {
                        header: "label",
                        value: "Feb 2025",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 0,
                        FACEBOOK: 1,
                        VOICE_CALL: 23,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 18,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Mar 2025",
                    shortLabel: "Mar '25",
                    totalCount: 15,
                    startDate: "03/01/2025",
                    endDate: "03/31/2025",
                    dynamicLabel: {
                        header: "label",
                        value: "Mar 2025",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 0,
                        FACEBOOK: 0,
                        VOICE_CALL: 10,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 4,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 1,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Apr 2025",
                    shortLabel: "Apr '25",
                    totalCount: 30,
                    startDate: "04/01/2025",
                    endDate: "04/30/2025",
                    dynamicLabel: {
                        header: "label",
                        value: "Apr 2025",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 1,
                        FACEBOOK: 0,
                        VOICE_CALL: 24,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 5,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 0,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "May 2025",
                    shortLabel: "May '25",
                    totalCount: 32,
                    startDate: "05/01/2025",
                    endDate: "05/31/2025",
                    dynamicLabel: {
                        header: "label",
                        value: "May 2025",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 3,
                        FACEBOOK: 0,
                        VOICE_CALL: 17,
                        INSTAGRAM: 2,
                        TWITTER: 0,
                        SMS: 9,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 1,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
            {
                actual: {
                    label: "Jun 2025",
                    shortLabel: "Jun '25",
                    totalCount: 84,
                    startDate: "06/01/2025",
                    endDate: "06/28/2025",
                    dynamicLabel: {
                        header: "label",
                        value: "Jun 2025",
                        order: 2147483647,
                        cellType: "TEXT",
                    },
                    subDataPoints: {
                        WEB_CHAT: 9,
                        FACEBOOK: 2,
                        VOICE_CALL: 44,
                        INSTAGRAM: 0,
                        TWITTER: 0,
                        SMS: 15,
                        GOOGLE: 0,
                        APPLE: 0,
                        EMAIL: 14,
                        CONTACT_US: 0,
                        APPOINTMENT: 0,
                    },
                },
            },
        ],
        groupByType: "month",
        dateDiff: 365,
    },
    isInsightsAvailable: true,
    legendValue: null,
    yAxisOptions: {
        enableDoubleYAxis: false,
        leftYAxisOptions: {
            label: "Messages received by channel",
            min: 0,
            max: 0,
        },
        rightYAxisOptions: null,
    },
    isDefaultComparisonFilterApplied: false,
    displayUnit: null,
    apiDetails: {
        isReportsEnabled: 1,
        roleBaseKey: "messenger",
        url: "inbox/report/by-channel/received-messages",
        method: "post",
        mockResponse: {
            groupByType: "month",
            dateDiff: 365,
            summary: {
                actual: {
                    totalCount: 1365,
                    thisMonth: 127,
                    lastOneYear: 1365,
                },
            },
            dataPoints: [
                {
                    actual: {
                        label: "Sep 2022",
                        shortLabel: "Sep 2022",
                        startDate: "09/22/2022",
                        endDate: "09/30/2022",
                        totalCount: 0,
                        receivedMessageCount: 34,
                    },
                },
            ],
        },
    },
    isVisible: true,
    mainHeading: "Channels",
    graphId: "channels-received-messages",
    isRaceChartDownload: false,
    subModule: "inbox",
    module: "inbox",
    layoutConfig: {
        maxH: 8,
        minW: 6,
        h: 4,
        i: "grid_id",
        maxW: 12,
        minH: 4,
        w: 12,
        x: 0,
        y: null,
    },
    defaultLayoutSize: "M",
    supportedFilters: {
        reviewSources: false,
        reportSources: true,
        users: false,
        experienceScore: true,
        timePeriod: true,
        locationAndHierarchy: true,
        reviewRating: false,
        customerType: true,
        surveyScore: true,
        tags: false,
    },
    displayUnits: [
        {
            label: "Shortened number",
            value: "SHORT_NUM",
        },
        {
            label: "Full number",
            value: "FULL_NUM",
        },
        {
            label: "Hundreds",
            value: "H",
        },
        {
            label: "Thousands",
            value: "K",
        },
        {
            label: "Millions",
            value: "M",
        },
        {
            label: "Billions",
            value: "B",
        },
        {
            label: "Trillions",
            value: "T",
        },
    ],
    order: 1,
    subReportHeading: "Messages received by channel",
    hierarchyLevel: "",
    tagsAvailable: true,
    disabledSeries: [],
    redirectURL: "",
    visualizationTypes: ["spline", "bar", "column", "heatmap", "streamgraph", "area", "table"],
    finalPayload: {
        groupByType: "",
        months: "12",
        key: "last_12_months",
        requireCumulative: false,
        newFilters: false,
        socialChannels: [],
    },
    displayBy: {
        daily: true,
        weekly: true,
        monthly: true,
        quarterly: true,
        yearly: true,
    },
    hideNonRequiredVisualizations: true,
    compareOptions: [],
    isDefaultEditable: false,
    showDelta: true,
    tagIds: [],
    chartActions: [{}],
    globalFilters: {
        months: "12",
        key: "last_12_months",
        businessIds: [],
        currentChange: null,
        localFilter: false,
        reviewSites: [],
        reportSources: [],
        customerSentiment: [],
        employeeIds: [],
        fieldFilters: [],
        surveyIds: [],
        excludedBizIds: [],
        messages: [],
        questionType: [],
    },
    gridItemStyle: {
        height: 552,
        width: 1123,
    },
    filterCount: {
        "channels-received-messages": 0,
    },
    isFullWidthEnabled: true,
    router: "/dashboard/analytics-dash/reports/inbox/channels/inbox",
    createdBy: "",
    disabledSeriesData: [],
};
