/**
 * Action types for Copilot chat state management
 * These constants are used with the useReducer hook to manage chat state
 */
export const ACTIONS = {
  // Message management
  ADD_MESSAGE: "ADD_MESSAGE",
  CLEAR_MESSAGES: "CLEAR_MESSAGES",
  CLEAR_NEW_MESSAGE_DIVIDER: "CLEAR_NEW_MESSAGE_DIVIDER",
  UPDATE_MESSAGE_SUGGESTION_STATE: "UPDATE_MESSAGE_SUGGESTION_STATE",
  UPDATE_MESSAGE_ACTION_STATE: "UPDATE_MESSAGE_ACTION_STATE",
  UPDATE_FILE_HANDLE_STATE: "UPDATE_FILE_HANDLE_STATE",
  UPDATE_INPUT_LABEL_STATE: "UPDATE_INPUT_LABEL_STATE",
  UPDATE_SELECT_STATE: "UPDATE_SELECT_STATE",
  UPDATE_CUSTOM_FIELD_SELECTION_STATE: "UPDATE_CUSTOM_FIELD_SELECTION_STATE",
  UPDATE_MULTISELECT_DROPDOWN_STATE: "UPDATE_MULTISELECT_DROPDOWN_STATE",
  UPDATE_STEPPER_STATE: "UPDATE_STEPPER_STATE",
  UPDATE_REPORT_SELECTION_STATE: "UPDATE_REPORT_SELECTION_STATE",
  REMOVE_COMPLETED_STEPPER: "REMOVE_COMPLETED_STEPPER",
  REMOVE_COMPONENT_BY_MESSAGE_ID: "REMOVE_COMPONENT_BY_MESSAGE_ID",
  REMOVE_COMPONENT_BY_COMPONENT_ID: "REMOVE_COMPONENT_BY_COMPONENT_ID",
  REMOVE_MESSAGE_BY_COMPONENT_ID: "REMOVE_MESSAGE_BY_COMPONENT_ID",
  REMOVE_LAST_MESSAGE: "REMOVE_LAST_MESSAGE",
  // Loading and error states
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  
  // Chat history management
  TOGGLE_HISTORY: "TOGGLE_HISTORY",
  SET_HISTORY_LOADING: "SET_HISTORY_LOADING",
  LOAD_HISTORY_CHAT: "LOAD_HISTORY_CHAT",
  SAVE_CHAT_TO_HISTORY: "SAVE_CHAT_TO_HISTORY",
  UPDATE_CURRENT_CHAT: "UPDATE_CURRENT_CHAT",
  SET_CURRENT_CHAT_ID: "SET_CURRENT_CHAT_ID",
  SET_CHAT_HISTORY: "SET_CHAT_HISTORY",
  
  // UI actions
  TRIGGER_SCROLL_TO_BOTTOM: "TRIGGER_SCROLL_TO_BOTTOM",
  
  // Pagination actions
  SET_PAGINATION_LOADING: "SET_PAGINATION_LOADING",
  LOAD_MORE_MESSAGES: "LOAD_MORE_MESSAGES",
  RESET_PAGINATION: "RESET_PAGINATION",
  SET_PAGINATION_DATA: "SET_PAGINATION_DATA",
};
