export const pieConfig = {
  reportsGroup: "response-time-distribution",
  disableEmailBodyEdit: false,
  tempUniqueId: "average-response-time-distribution_175368695195086",
  subReportsGroup: "response-time-distribution",
  parserConfig: {
    percentageGrowthIsNegative: true,
    dataFormat: "grouped",
    categoryKey: "avgResponseByRating",
    displaySummary: false,
    crosshairConfig: {
      color: "#e3effc",
    },
    showTimeUnitInTooltipLabel: true,
    showProjectedData: false,
    yAxisText: "Response time",
    categoryValueMap: {
      "0": {
        value: "No rating",
        color: "#CCCCCC",
        compareColor: "#E5E5E5",
      },
      "1": {
        value: "1 star",
        color: "#DE1B0C",
        compareColor: "#F99E8F",
      },
      "2": {
        value: "2 star",
        color: "#FF6A4D",
        compareColor: "#FFB9A7",
      },
      "3": {
        value: "3 star",
        color: "#FBC123",
        compareColor: "#FEE1A5",
      },
      "4": {
        value: "4 star",
        color: "#7ED321",
        compareColor: "#C0EBA2",
      },
      "5": {
        value: "5 star",
        color: "#4CAE3D",
        compareColor: "#A9D8A2",
      },
    },
    doubleYaxis: false,
    graphTitle: "Response time distribution",
    xAxisLabelsAlignment: {
      bar: "right",
      column: "center",
      spline: "center",
    },
    seriesDetails: [
      {
        primary: true,
        color: "#ccc",
        showDisplayUnits: true,
        name: "Response time",
        tableViewkey: "ratingOrderData",
        showInLegend: false,
        dataKey: "avgResponseTime",
        maxPointWidth: 20,
        type: "pie",
        yAxisLabel: "Review time",
        id: "barProjected",
      },
    ],
    dataPoints: false,
    plotDataConfig: [
      {
        dataLabels: {
          enabled: true,
          showUnitInBracket: true,
          color: "#212121",
          stackLabels: false,
          fontWeight: 400,
          verticalAlign: "top",
          fontSize: "12px",
          y: -15,
        },
        stacking: "normal",
        inside: false,
        type: "column",
        compareStacking: "normal",
      },
      {
        dataLabels: {
          enabled: true,
          verticalAlign: "middle",
          format: "{point.y}",
          fontSize: "12px",
          fontWeight: 400,
          color: "#212121",
          text: "",
        },
        stacking: "normal",
        inside: false,
        type: "bar",
      },
      {
        dataLabels: {
          color: "#fff",
          fontSize: "12px",
          fontWeight: 400,
          verticalAlign: "middle",
          enabled: false,
        },
        type: "spline",
      },
      {
        dataLabels: {
          allowOverlap: false,
          crop: false,
          overflow: "none",
          inside: false,
        },
        minPointLength: 3,
        marker: {
          enabled: true,
        },
        type: "series",
      },
    ],
    marginRight: 0,
    lineChartComparisonEnabled: true,
    tableConfig: {
      actual: [
        {
          dataLabel: "Rating",
          dataKey: "starRating",
          width: 150,
          enableSort: true,
          columnKey: "rating",
        },
        {
          dataLabel: "Review time",
          dataKey: "totalCount",
          width: 150,
          enableSort: true,
          columnKey: "count",
        },
      ],
      compare: [
        {
          dataLabel: "Rating",
          dataKey: "starRating",
          width: 200,
          enableSort: true,
          columnKey: "rating",
        },
        {
          dataKey: "totalCount",
          width: 130,
          enableSort: true,
          columnKey: "count_compare",
        },
        {
          dataKey: "totalCount",
          width: 130,
          enableSort: true,
          columnKey: "count",
        },
      ],
    },
    updateTooltipDotColorWithColumnColor: true,
    defaultChartStyle: "column",
    primaryChartStyle: "pie",
    marginLeft: 0,
    reportOverTime: false,
    hideDottedLastLine: true,
    selectedDisplayValueAs: "days",
    categoryList: ["0", "1", "2", "3", "4", "5"],
    compareStacking: "normal",
    enableCrosshair: true,
    reverseLegendOrder: false,
  },
  displayValueAs: {
    days: true,
    hours: true,
    minutes: true,
  },
  heading: "Response time distribution",
  actualAndCompareWith: {},
  globalFilterApplied: true,
  filterData: {
    questionType: [],
    comparisonFilter: null,
    filterData: false,
    reportSources: [],
    selectedMonth: [],
    isDefaultComparisonFilterApplied: false,
    selectedkeywords: [],
    ticketType: [],
    apiDetails: {
      params: {
        size: 100,
      },
      url: "review/report/avg-response-time/time-distribution",
      hierarchyRoleBaseKey: "",
      roleBaseKey: "reports/review_reports/response_time_distribution",
      method: "post",
    },
    employeeIds: [],
    experienceScores: [],
    messages: [],
    groupByDays: "1",
    userIds: [],
    reviewFilterOptions: [],
    excludedBizIds: [],
    groupByType: "",
    customerSentiment: [],
    selectedSeries: [],
    surveySites: [],
    chartStyle: "pie",
    reviewSites: [],
    allMonths: [],
    ratings: [],
    allSurveyDropdownData: {},
    days: "90",
    customerType: null,
    requireCumulative: false,
    employeeCodes: [],
    businessIds: [1287366],
    previousURL: "",
    finalPayload: {
      groupByType: "",
      days: "90",
      groupByDays: "1",
      businessIds: [1287366],
      newFilters: true,
      socialChannels: [],
      sizeParam: 100,
    },
    tags: [],
    surveyScores: [],
    newFilters: true,
    selectedDisplayValueAs: "",
    surveyIds: [],
    sourceTypes: [],
    socialSites: [],
  },
  apiData: {
    dataPoints: [
      {
        actual: {
          avgResponseByRating: {
            "0": {
              avgResponseTime: {
                days: 0,
                hours: 0,
                minutes: 0,
              },
              respondedCount: 0,
            },
            "1": {
              avgResponseTime: {
                days: 0.46,
                hours: 11.11,
                minutes: 666.75,
              },
              respondedCount: 1,
            },
            "2": {
              avgResponseTime: {
                days: 0,
                hours: 0,
                minutes: 0,
              },
              respondedCount: 0,
            },
            "3": {
              avgResponseTime: {
                days: 0,
                hours: 0,
                minutes: 0,
              },
              respondedCount: 0,
            },
            "4": {
              avgResponseTime: {
                days: 0.45,
                hours: 10.92,
                minutes: 655.07,
              },
              respondedCount: 1,
            },
            "5": {
              avgResponseTime: {
                days: 0.32,
                hours: 7.65,
                minutes: 458.83,
              },
              respondedCount: 33,
            },
          },
        },
      },
    ],
    dataPresent: true,
    dateDiff: 89,
    groupByType: "day",
  },
  isInsightsAvailable: true,
  legendValue: ["Different star ratings"],
  yAxisOptions: {
    enableDoubleYAxis: false,
    leftYAxisOptions: {
      label: "Review time",
      min: 0,
      max: 0,
    },
    rightYAxisOptions: null,
  },
  isDefaultComparisonFilterApplied: false,
  displayUnit: {
    value: true,
    percentage: true,
    supportedChart: "PC",
  },
  apiDetails: {
    isReportsEnabled: true,
    roleBaseKey: "reports/review_reports/response_time_distribution",
    url: "review/report/avg-response-time/time-distribution",
    method: "post",
    mockResponse: null,
  },
  isVisible: true,
  mainHeading: "Response time distribution",
  graphId: "average-response-time-distribution",
  isRaceChartDownload: false,
  subModule: "overview",
  module: "reviews",
  layoutConfig: {
    maxH: 8,
    minW: 6,
    h: 4,
    i: "grid_id",
    maxW: 12,
    minH: 4,
    w: 12,
    x: 0,
    y: null,
  },
  defaultLayoutSize: "M",
  supportedFilters: {
    timePeriod: true,
    locationAndHierarchy: true,
    reviewSources: true,
    reviewRating: true,
    users: false,
    tags: false,
  },
  displayUnits: [
    {
      label: "Shortened number",
      value: "SHORT_NUM",
    },
    {
      label: "Full number",
      value: "FULL_NUM",
    },
    {
      label: "Hundreds",
      value: "H",
    },
    {
      label: "Thousands",
      value: "K",
    },
    {
      label: "Millions",
      value: "M",
    },
    {
      label: "Billions",
      value: "B",
    },
    {
      label: "Trillions",
      value: "T",
    },
  ],
  order: 2,
  subReportHeading: "Response time distribution",
  hierarchyLevel: "",
  tagsAvailable: true,
  redirectURL: "/dashboard/reviews/feed?nav-tab=Custom&",
  extraReqParams: {
    sortOrder: 1,
    sortedColumn: "review-count",
  },
  errorCode: -1,
  visualizationTypes: ["column", "bar", "table", "pie", "spline"],
  finalPayload: {
    groupByType: "",
    days: "90",
    groupByDays: "1",
    businessIds: [1287366],
    requireCumulative: false,
    newFilters: true,
    socialChannels: [],
  },
  displayBy: {
    daily: false,
    weekly: false,
    monthly: false,
    quarterly: false,
    yearly: false,
  },
  compareOptions: ["TIME_PERIOD", "LOCATION"],
  isDefaultEditable: false,
  showDelta: true,
  tagIds: [],
  chartActions: [{}],
  globalFilters: {
    days: "90",
    groupByDays: "1",
    businessIds: [1287366],
    currentChange: {
      key: [],
    },
    localFilter: false,
    reviewSites: [],
    reportSources: [],
    ticketType: [],
    customerSentiment: [],
    employeeIds: [],
    fieldFilters: [],
    surveyIds: [],
    excludedBizIds: [],
    messages: [],
    questionType: [],
    selectedkeywords: [],
  },
  gridItemStyle: {
    height: 552,
    width: 1123,
  },
  filterCount: {
    "average-response-time-distribution": 0,
    "responded-review-distribution": 0,
  },
  isFullWidthEnabled: true,
  router:
    "/dashboard/analytics-dash/reports/reviews/response-time-distribution/overview",
  createdBy: "",
  sideDrawerDetails: {},
  disabledSeriesData: [],
};
